# Generated by Django 5.1.7 on 2025-03-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_aboutvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='budget_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.budgetrange'),
        ),
    ]
