# Generated by Django 5.1.7 on 2025-03-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_budgetrange_alter_quoterequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.budgetrange'),
        ),
    ]
