# Generated by Django 5.1.7 on 2025-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_project_budget_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sq_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
