# Generated by Django 5.1.7 on 2025-03-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/upcoming/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sq_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.budgetrange')),
            ],
        ),
    ]
