# Generated by Django 5.1.7 on 2025-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bhk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upcomingproject',
            name='bhk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
