# Generated by Django 5.1.7 on 2025-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_project_bhk_upcomingproject_bhk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about_images/')),
                ('author_name', models.CharField(max_length=100)),
                ('author_designation', models.CharField(max_length=100)),
            ],
        ),
    ]
