# Generated by Django 5.1.7 on 2025-04-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_projectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Optional: YouTube link for client reference', null=True),
        ),
    ]
