# Generated by Django 5.1.7 on 2025-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_projectvideo_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='youtube_link',
            field=models.CharField(blank=True, help_text='Only enter the 11-character YouTube video ID', max_length=11, null=True),
        ),
    ]
