# Generated by Django 5.1.7 on 2025-04-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_youtubevideo_remove_projectvideo_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingproject',
            options={'verbose_name_plural': 'Ongoing projects'},
        ),
    ]
