# Generated by Django 5.1.7 on 2025-04-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_upcomingproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'video testimonials'},
        ),
    ]
