# Generated by Django 5.1.7 on 2025-04-09 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
