# Generated by Django 5.1.7 on 2025-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('office', 'Office')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
