# Generated by Django 5.1.7 on 2025-04-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
