# Generated by Django 5.1.7 on 2025-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_homeslider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='healine',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeslider',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='sub_headline',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
