# Generated by Django 5.1.7 on 2025-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_slidervideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTitleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='about-head/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slidervideo',
            name='video_file',
            field=models.FileField(upload_to='contact-slider/'),
        ),
    ]
