# Generated by Django 5.1.7 on 2025-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_abouttitlevideo_alter_slidervideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('interior', 'interior')], max_length=20),
        ),
    ]
