# Generated by Django 5.2.1 on 2025-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_project_status_upcomingproject_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='abouttitlevideo',
            name='video_file',
            field=models.FileField(upload_to='about-head/'),
        ),
        migrations.AlterField(
            model_name='aboutvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(upload_to='home_slider/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects-img/'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video_file',
            field=models.FileField(upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='slidervideo',
            name='video_file',
            field=models.FileField(upload_to='contact-slider/'),
        ),
        migrations.AlterField(
            model_name='upcomingproject',
            name='image',
            field=models.ImageField(upload_to='upcomming-project-img/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='testimonals/videos/'),
        ),
    ]
