# Generated by Django 5.2.1 on 2025-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_aboutsection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='projects-img/'),
        ),
    ]
