# Generated by Django 5.2.1 on 2025-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_project_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
