# Generated by Django 5.2.1 on 2025-07-19 10:10

from django.db import migrations, models
import index.utils


def populate_slugs(apps, schema_editor):
    Project = apps.get_model('index', 'Project')
    for project in Project.objects.all():
        if not project.slug:
            project.slug = index.utils.generate_unique_slug(Project, project.name)
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_remove_video_video_file_video_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(populate_slugs),  # Add this step
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, blank=True),
        ),
        migrations.AddField(
            model_name='upcomingproject',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]

