# Generated by Django 5.2.1 on 2025-07-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_project_slug_upcomingproject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingproject',
            name='slug',
        ),
    ]
