# Generated by Django 5.2.1 on 2025-07-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0032_project_slug_upcomingproject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
