# Generated by Django 5.2.1 on 2025-12-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_seoservicepage_seoserviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_link',
            field=models.URLField(help_text='Paste full YouTube URL or video ID', max_length=500),
        ),
    ]
