# Generated by Django 5.2.1 on 2025-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_alter_youtubevideo_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='aboutvideo',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Paste YouTube URL or video ID', max_length=500, null=True),
        ),
    ]
